import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs/promises';

// Same regex the CLI itself enforces. Anything else is rejected before we shell out.
export const SLUG_RE = /^[a-z][a-z0-9-]+[a-z0-9]$/;

export function projectDir(): string {
    // When the portal runs in-repo (next dev/start from portal/), the orchestrator lives one level up.
    return process.env.AKDMI_PROJECT_DIR
        ? path.resolve(process.env.AKDMI_PROJECT_DIR)
        : path.resolve(process.cwd(), '..');
}

export function akdmiBin(): string {
    return path.join(projectDir(), 'akd-mi');
}

export type CliResult = { ok: boolean; code: number; stdout: string; stderr: string };

export async function runAkdmi(args: string[], opts: { timeoutMs?: number; env?: Record<string, string> } = {}): Promise<CliResult> {
    const timeoutMs = opts.timeoutMs ?? 5 * 60 * 1000;
    return new Promise((resolve) => {
        const child = spawn('bash', [akdmiBin(), ...args], {
            cwd: projectDir(),
            env: { ...process.env, ...(opts.env ?? {}) },
        });
        let stdout = '', stderr = '';
        let killed = false;
        const t = setTimeout(() => { killed = true; child.kill('SIGKILL'); }, timeoutMs);
        child.stdout.on('data', (d) => { stdout += d.toString(); });
        child.stderr.on('data', (d) => { stderr += d.toString(); });
        child.on('error', (e) => {
            clearTimeout(t);
            resolve({ ok: false, code: -1, stdout, stderr: stderr + '\n' + String(e) });
        });
        child.on('close', (code) => {
            clearTimeout(t);
            resolve({ ok: !killed && code === 0, code: code ?? -1, stdout, stderr: killed ? stderr + '\n[killed: timeout]' : stderr });
        });
    });
}

/** Parse the .env file generated by `akd-mi init` to extract URLs + admin credentials. */
export async function readInstanceEnv(slug: string): Promise<Record<string, string>> {
    if (!SLUG_RE.test(slug)) throw new Error('invalid slug');
    const envPath = path.join(projectDir(), 'instances', slug, '.env');
    const txt = await fs.readFile(envPath, 'utf8');
    const out: Record<string, string> = {};
    for (const raw of txt.split('\n')) {
        const line = raw.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq <= 0) continue;
        out[line.slice(0, eq)] = line.slice(eq + 1);
    }
    return out;
}

export async function instanceDirExists(slug: string): Promise<boolean> {
    try {
        const s = await fs.stat(path.join(projectDir(), 'instances', slug));
        return s.isDirectory();
    } catch { return false; }
}

/** Return every slug under `instances/` that has a `.env` file (so it was actually initialised). */
export async function listInstanceDirs(): Promise<string[]> {
    const root = path.join(projectDir(), 'instances');
    let entries: string[];
    try { entries = await fs.readdir(root); }
    catch { return []; }
    const out: string[] = [];
    for (const name of entries) {
        if (!SLUG_RE.test(name)) continue;
        try {
            const st = await fs.stat(path.join(root, name));
            if (!st.isDirectory()) continue;
            const envSt = await fs.stat(path.join(root, name, '.env'));
            if (envSt.isFile()) out.push(name);
        } catch { /* skip */ }
    }
    return out.sort();
}

/** True iff at least one container labelled with this instance's compose project is up. */
export async function isInstanceRunning(slug: string): Promise<boolean> {
    if (!SLUG_RE.test(slug)) return false;
    return new Promise((resolve) => {
        const child = spawn('docker', [
            'ps', '--filter', `label=com.docker.compose.project=akdmi-${slug}`, '--format', '{{.ID}}',
        ]);
        let out = '';
        child.stdout.on('data', (d) => { out += d.toString(); });
        child.on('error', () => resolve(false));
        child.on('close', () => resolve(out.trim().length > 0));
    });
}
